const $=id=>document.getElementById(id), token=document.querySelector('meta[name=setup-token]').content;
let state=null,polling=false;
function notice(message,error=false){$('notice').hidden=false;$('notice').textContent=message;$('notice').className=error?'error':''}
async function api(path,data){const options={headers:{'X-Setup-Token':token}};if(data!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(data)}const r=await fetch('/api/'+path,options);const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result}
async function action(fn){try{await fn()}catch(e){notice(e.message,true)}}
function updateMode(){const chosen=document.querySelector('[name=provider]:checked').value;
 $('localSetup').hidden=chosen!=='local';$('cloudKey').hidden=chosen==='local';$('cloudKeyHelp').hidden=chosen==='local';$('verifyOpenai').hidden=chosen==='local';
 const mode=state?.configured?state.provider:chosen;
 $('draftOptions').hidden=mode==='local';if(mode==='local')$('questions').checked=false;
 $('consentText').textContent=mode==='local'?'I can use this content. Local transcription and keyword search stay on this computer.':'I can use this content and approve sending it to OpenAI for paid processing.';
 $('searchScope').textContent=mode==='local'?'This mode uses local keyword search. The recording and search queries are not sent to an AI provider.':'In OpenAI mode, searching sends your query to the embedding provider and can incur charges.';
}
for(const radio of document.querySelectorAll('[name=provider]'))radio.onchange=updateMode;
function panel(name){for(const s of ['setup','import','archive'])$(s).hidden=s!==name;for(const b of document.querySelectorAll('.tab'))b.classList.toggle('selected',b.dataset.panel===name)}
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>panel(b.dataset.panel);
function element(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
async function refresh(){state=await api('status');$('system').textContent=`Python ${state.runtime}\n${state.free_gb} GB free storage\nMedia tools: ${state.ffprobe?'ready':'install FFmpeg for audio'}\n${state.documents} archived recordings${state.provider==='local'?'\nLocal Whisper: '+(state.local.whisper_cli?'ready':'missing')+'\nModel: '+(state.local.model?'ready':'missing'):''}`;updateMode();$('connectionStatus').textContent=Object.entries(state.connections).map(([k,v])=>k+': '+(v.verified?'verified':v.configured?'configured, not verified':'not connected')).join(' · ');$('jobs').replaceChildren();for(const job of state.jobs){const box=element('div','', 'item');box.append(element('div',job.status+' · '+job.stage,'badge'),element('strong',job.title),element('p',job.message));if(job.status!=='running'&&job.status!=='complete'){const b=element('button',job.status==='ready'?'Start processing':'Resume import');b.onclick=()=>action(async()=>{await api('start',{id:job.id});await refresh()});box.append(b)}if(job.status==='complete'){const b=element('button','Open archive','secondary');b.onclick=()=>action(async()=>{panel('archive');await archive()});box.append(b)}$('jobs').append(box)}if(!state.jobs.length)$('jobs').textContent='No imports yet.'}
$('connections').onsubmit=e=>{e.preventDefault();action(async()=>{const data={provider:document.querySelector('[name=provider]:checked').value};for(const key of ['openai','youtube'])if($(key).value.trim())data[key]=$(key).value.trim();await api('configure',data);$('openai').value='';$('youtube').value='';await refresh();notice(data.provider==='local'?'Local processing selected. No AI provider key is needed.':'Setup saved. Entered keys remain in memory for this session.');panel('import')})};
$('verifyOpenai').onclick=()=>action(async()=>{notice((await api('verify',{service:'openai'})).message);await refresh()});$('verifyYoutube').onclick=()=>action(async()=>{notice((await api('verify',{service:'youtube'})).message);await refresh()});
$('disconnect').onclick=()=>action(async()=>{await api('configure',{openai:'',youtube:'',provider:state.provider});await refresh();notice('Session keys cleared.')});
$('example').onclick=()=>action(async()=>{await api('configure',{provider:'fixture'});const job=await api('create',{example:true});await api('start',{id:job.id});panel('import');await refresh();notice('Example import started. No accounts or paid calls are used.')});
$('discover').onsubmit=e=>{e.preventDefault();action(async()=>{notice('Finding recording references…');const result=await api('discover',{url:$('url').value});$('discovered').replaceChildren();for(const item of result.items){const box=element('div','','item');const b=element('button','Select recording','secondary');b.onclick=()=>{$('source').value=item.url;$('title').value=item.title;notice('Selected. Attach its transcript or recording below.')};box.append(element('strong',item.title),element('p',item.availability),b);$('discovered').append(box)}notice(result.note+(result.items.length?'':' No YouTube links found.'))})};
$('file').onchange=()=>{const f=$('file').files[0],local=state?.provider==='local';$('estimate').textContent=f?`${f.name} · ${(f.size/1e6).toFixed(2)} MB\nOne recording. ${f.name.toLowerCase().endsWith('.vtt')?'Transcription skipped.':'Duration checked before '+(local?'local Whisper transcription.':'cloud transcription.')}\n${local?'Local keyword search, no AI provider charges.':'Provider charges depend on duration and text. Import limit: 300,000 embedding input characters. No guaranteed dollar cap.'}`:'Choose a file to preview the work.'};
function encoded(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read file'));reader.readAsDataURL(file)})}
$('upload').onsubmit=e=>{e.preventDefault();action(async()=>{const file=$('file').files[0];const limit=state.provider==='local'?50_000_000:20_000_000;if(!file||file.size>limit)throw Error('Choose a file no larger than '+(limit/1e6)+' MB.');const button=$('upload').querySelector('button');button.disabled=true;try{const job=await api('create',{title:$('title').value,source:$('source').value,filename:file.name,file:await encoded(file),questions:$('questions').checked,paid:$('paid').checked});await refresh();notice('Import saved. Review it below, then start processing.');$('jobs').scrollIntoView({block:'nearest'})}finally{button.disabled=false}})};
function timestamp(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
async function archive(){const result=await api('archive');$('documents').replaceChildren();for(const doc of result.documents){const d=document.createElement('details');d.append(element('summary',doc.title));if(doc.source){const a=element('a','Original recording');a.href=doc.source;a.target='_blank';a.rel='noreferrer';d.append(a)}for(const cue of doc.cues){const p=element('p','','cue');p.append(element('small',timestamp(cue.start)),document.createTextNode(cue.text));d.append(p)}$('documents').append(d)}for(const draft of result.drafts){if(!draft.items.length)continue;const box=element('div','','item');box.append(element('h3',draft.title+' · Question drafts'),element('p','These answers are source excerpts. Review whether each question accurately represents the speaker. Nothing is published.'));for(const q of draft.items)box.append(element('strong',q.question),element('p',q.answer),element('small',timestamp(q.start)+' · '+q.status));$('documents').append(box)}if(!result.documents.length)$('documents').textContent='Import a recording to open its archive.';return result}
$('refreshArchive').onclick=()=>action(archive);$('export').onclick=()=>action(async()=>{const data=await api('archive'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='content-archive.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('search').onsubmit=e=>{e.preventDefault();action(async()=>{const result=await api('search',{query:$('query').value});$('results').replaceChildren();for(const r of result.results){const box=element('div','','item');box.append(element('strong',r.title),element('p',r.text),element('small',timestamp(r.start)+' · '+r.lanes.join(' + ')));$('results').append(box)}notice(result.degraded?'Vector service unavailable. Showing keyword results.':result.results.length+' matching sources.');if(!result.results.length)$('results').textContent='No supported passage found.'})};
action(async()=>{await refresh();document.querySelector(`[name=provider][value=${state.provider}]`).checked=true;updateMode();if(state.configured)panel(state.documents?'archive':'import')});setInterval(async()=>{if(polling)return;polling=true;try{await refresh()}catch(e){}finally{polling=false}},2500);
